# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sandbox_pb2 as sandbox__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunCommand = channel.unary_unary(
                '/sandbox.SandboxService/RunCommand',
                request_serializer=sandbox__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=sandbox__pb2.RunCommandResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/sandbox.SandboxService/WriteFile',
                request_serializer=sandbox__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=sandbox__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/sandbox.SandboxService/ReadFile',
                request_serializer=sandbox__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=sandbox__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.SetEnv = channel.unary_unary(
                '/sandbox.SandboxService/SetEnv',
                request_serializer=sandbox__pb2.SetEnvRequest.SerializeToString,
                response_deserializer=sandbox__pb2.SetEnvResponse.FromString,
                _registered_method=True)
        self.SetCwd = channel.unary_unary(
                '/sandbox.SandboxService/SetCwd',
                request_serializer=sandbox__pb2.SetCwdRequest.SerializeToString,
                response_deserializer=sandbox__pb2.SetCwdResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunCommand(self, request, context):
        """Run command in session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """File operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEnv(self, request, context):
        """Environment/CWD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCwd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCommand,
                    request_deserializer=sandbox__pb2.RunCommandRequest.FromString,
                    response_serializer=sandbox__pb2.RunCommandResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=sandbox__pb2.WriteFileRequest.FromString,
                    response_serializer=sandbox__pb2.WriteFileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=sandbox__pb2.ReadFileRequest.FromString,
                    response_serializer=sandbox__pb2.ReadFileResponse.SerializeToString,
            ),
            'SetEnv': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEnv,
                    request_deserializer=sandbox__pb2.SetEnvRequest.FromString,
                    response_serializer=sandbox__pb2.SetEnvResponse.SerializeToString,
            ),
            'SetCwd': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCwd,
                    request_deserializer=sandbox__pb2.SetCwdRequest.FromString,
                    response_serializer=sandbox__pb2.SetCwdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sandbox.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/RunCommand',
            sandbox__pb2.RunCommandRequest.SerializeToString,
            sandbox__pb2.RunCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/WriteFile',
            sandbox__pb2.WriteFileRequest.SerializeToString,
            sandbox__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/ReadFile',
            sandbox__pb2.ReadFileRequest.SerializeToString,
            sandbox__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEnv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/SetEnv',
            sandbox__pb2.SetEnvRequest.SerializeToString,
            sandbox__pb2.SetEnvResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCwd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sandbox.SandboxService/SetCwd',
            sandbox__pb2.SetCwdRequest.SerializeToString,
            sandbox__pb2.SetCwdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
