// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/worker/worker.proto

package worker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxWorker_CreateSandbox_FullMethodName     = "/worker.SandboxWorker/CreateSandbox"
	SandboxWorker_DestroySandbox_FullMethodName    = "/worker.SandboxWorker/DestroySandbox"
	SandboxWorker_GetSandbox_FullMethodName        = "/worker.SandboxWorker/GetSandbox"
	SandboxWorker_ListSandboxes_FullMethodName     = "/worker.SandboxWorker/ListSandboxes"
	SandboxWorker_ExecCommand_FullMethodName       = "/worker.SandboxWorker/ExecCommand"
	SandboxWorker_ExecCommandStream_FullMethodName = "/worker.SandboxWorker/ExecCommandStream"
	SandboxWorker_ReadFile_FullMethodName          = "/worker.SandboxWorker/ReadFile"
	SandboxWorker_WriteFile_FullMethodName         = "/worker.SandboxWorker/WriteFile"
	SandboxWorker_ListDir_FullMethodName           = "/worker.SandboxWorker/ListDir"
	SandboxWorker_CreatePTY_FullMethodName         = "/worker.SandboxWorker/CreatePTY"
	SandboxWorker_PTYStream_FullMethodName         = "/worker.SandboxWorker/PTYStream"
	SandboxWorker_HibernateSandbox_FullMethodName  = "/worker.SandboxWorker/HibernateSandbox"
	SandboxWorker_WakeSandbox_FullMethodName       = "/worker.SandboxWorker/WakeSandbox"
	SandboxWorker_BuildTemplate_FullMethodName     = "/worker.SandboxWorker/BuildTemplate"
)

// SandboxWorkerClient is the client API for SandboxWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SandboxWorkerClient interface {
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc.CallOption) (*DestroySandboxResponse, error)
	GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error)
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (*ExecCommandResponse, error)
	ExecCommandStream(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutputChunk], error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	CreatePTY(ctx context.Context, in *CreatePTYRequest, opts ...grpc.CallOption) (*CreatePTYResponse, error)
	PTYStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PTYInput, PTYOutput], error)
	HibernateSandbox(ctx context.Context, in *HibernateSandboxRequest, opts ...grpc.CallOption) (*HibernateSandboxResponse, error)
	WakeSandbox(ctx context.Context, in *WakeSandboxRequest, opts ...grpc.CallOption) (*WakeSandboxResponse, error)
	BuildTemplate(ctx context.Context, in *BuildTemplateRequest, opts ...grpc.CallOption) (*BuildTemplateResponse, error)
}

type sandboxWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxWorkerClient(cc grpc.ClientConnInterface) SandboxWorkerClient {
	return &sandboxWorkerClient{cc}
}

func (c *sandboxWorkerClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_CreateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) DestroySandbox(ctx context.Context, in *DestroySandboxRequest, opts ...grpc.CallOption) (*DestroySandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySandboxResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_DestroySandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_GetSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_ListSandboxes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (*ExecCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecCommandResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_ExecCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) ExecCommandStream(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxWorker_ServiceDesc.Streams[0], SandboxWorker_ExecCommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecCommandRequest, ExecOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxWorker_ExecCommandStreamClient = grpc.ServerStreamingClient[ExecOutputChunk]

func (c *sandboxWorkerClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) CreatePTY(ctx context.Context, in *CreatePTYRequest, opts ...grpc.CallOption) (*CreatePTYResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePTYResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_CreatePTY_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) PTYStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PTYInput, PTYOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxWorker_ServiceDesc.Streams[1], SandboxWorker_PTYStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PTYInput, PTYOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxWorker_PTYStreamClient = grpc.BidiStreamingClient[PTYInput, PTYOutput]

func (c *sandboxWorkerClient) HibernateSandbox(ctx context.Context, in *HibernateSandboxRequest, opts ...grpc.CallOption) (*HibernateSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HibernateSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_HibernateSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) WakeSandbox(ctx context.Context, in *WakeSandboxRequest, opts ...grpc.CallOption) (*WakeSandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WakeSandboxResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_WakeSandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxWorkerClient) BuildTemplate(ctx context.Context, in *BuildTemplateRequest, opts ...grpc.CallOption) (*BuildTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildTemplateResponse)
	err := c.cc.Invoke(ctx, SandboxWorker_BuildTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxWorkerServer is the server API for SandboxWorker service.
// All implementations must embed UnimplementedSandboxWorkerServer
// for forward compatibility.
type SandboxWorkerServer interface {
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	DestroySandbox(context.Context, *DestroySandboxRequest) (*DestroySandboxResponse, error)
	GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error)
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	ExecCommand(context.Context, *ExecCommandRequest) (*ExecCommandResponse, error)
	ExecCommandStream(*ExecCommandRequest, grpc.ServerStreamingServer[ExecOutputChunk]) error
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	CreatePTY(context.Context, *CreatePTYRequest) (*CreatePTYResponse, error)
	PTYStream(grpc.BidiStreamingServer[PTYInput, PTYOutput]) error
	HibernateSandbox(context.Context, *HibernateSandboxRequest) (*HibernateSandboxResponse, error)
	WakeSandbox(context.Context, *WakeSandboxRequest) (*WakeSandboxResponse, error)
	BuildTemplate(context.Context, *BuildTemplateRequest) (*BuildTemplateResponse, error)
	mustEmbedUnimplementedSandboxWorkerServer()
}

// UnimplementedSandboxWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxWorkerServer struct{}

func (UnimplementedSandboxWorkerServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedSandboxWorkerServer) DestroySandbox(context.Context, *DestroySandboxRequest) (*DestroySandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySandbox not implemented")
}
func (UnimplementedSandboxWorkerServer) GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedSandboxWorkerServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedSandboxWorkerServer) ExecCommand(context.Context, *ExecCommandRequest) (*ExecCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedSandboxWorkerServer) ExecCommandStream(*ExecCommandRequest, grpc.ServerStreamingServer[ExecOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method ExecCommandStream not implemented")
}
func (UnimplementedSandboxWorkerServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxWorkerServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxWorkerServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedSandboxWorkerServer) CreatePTY(context.Context, *CreatePTYRequest) (*CreatePTYResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePTY not implemented")
}
func (UnimplementedSandboxWorkerServer) PTYStream(grpc.BidiStreamingServer[PTYInput, PTYOutput]) error {
	return status.Error(codes.Unimplemented, "method PTYStream not implemented")
}
func (UnimplementedSandboxWorkerServer) HibernateSandbox(context.Context, *HibernateSandboxRequest) (*HibernateSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HibernateSandbox not implemented")
}
func (UnimplementedSandboxWorkerServer) WakeSandbox(context.Context, *WakeSandboxRequest) (*WakeSandboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WakeSandbox not implemented")
}
func (UnimplementedSandboxWorkerServer) BuildTemplate(context.Context, *BuildTemplateRequest) (*BuildTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildTemplate not implemented")
}
func (UnimplementedSandboxWorkerServer) mustEmbedUnimplementedSandboxWorkerServer() {}
func (UnimplementedSandboxWorkerServer) testEmbeddedByValue()                       {}

// UnsafeSandboxWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxWorkerServer will
// result in compilation errors.
type UnsafeSandboxWorkerServer interface {
	mustEmbedUnimplementedSandboxWorkerServer()
}

func RegisterSandboxWorkerServer(s grpc.ServiceRegistrar, srv SandboxWorkerServer) {
	// If the following call panics, it indicates UnimplementedSandboxWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxWorker_ServiceDesc, srv)
}

func _SandboxWorker_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_DestroySandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).DestroySandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_DestroySandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).DestroySandbox(ctx, req.(*DestroySandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).GetSandbox(ctx, req.(*GetSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_ExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_ExecCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).ExecCommand(ctx, req.(*ExecCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_ExecCommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxWorkerServer).ExecCommandStream(m, &grpc.GenericServerStream[ExecCommandRequest, ExecOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxWorker_ExecCommandStreamServer = grpc.ServerStreamingServer[ExecOutputChunk]

func _SandboxWorker_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_CreatePTY_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePTYRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).CreatePTY(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_CreatePTY_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).CreatePTY(ctx, req.(*CreatePTYRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_PTYStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxWorkerServer).PTYStream(&grpc.GenericServerStream[PTYInput, PTYOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxWorker_PTYStreamServer = grpc.BidiStreamingServer[PTYInput, PTYOutput]

func _SandboxWorker_HibernateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HibernateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).HibernateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_HibernateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).HibernateSandbox(ctx, req.(*HibernateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_WakeSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WakeSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).WakeSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_WakeSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).WakeSandbox(ctx, req.(*WakeSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxWorker_BuildTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxWorkerServer).BuildTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxWorker_BuildTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxWorkerServer).BuildTemplate(ctx, req.(*BuildTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxWorker_ServiceDesc is the grpc.ServiceDesc for SandboxWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.SandboxWorker",
	HandlerType: (*SandboxWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _SandboxWorker_CreateSandbox_Handler,
		},
		{
			MethodName: "DestroySandbox",
			Handler:    _SandboxWorker_DestroySandbox_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _SandboxWorker_GetSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _SandboxWorker_ListSandboxes_Handler,
		},
		{
			MethodName: "ExecCommand",
			Handler:    _SandboxWorker_ExecCommand_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SandboxWorker_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SandboxWorker_WriteFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _SandboxWorker_ListDir_Handler,
		},
		{
			MethodName: "CreatePTY",
			Handler:    _SandboxWorker_CreatePTY_Handler,
		},
		{
			MethodName: "HibernateSandbox",
			Handler:    _SandboxWorker_HibernateSandbox_Handler,
		},
		{
			MethodName: "WakeSandbox",
			Handler:    _SandboxWorker_WakeSandbox_Handler,
		},
		{
			MethodName: "BuildTemplate",
			Handler:    _SandboxWorker_BuildTemplate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCommandStream",
			Handler:       _SandboxWorker_ExecCommandStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PTYStream",
			Handler:       _SandboxWorker_PTYStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/worker/worker.proto",
}
