// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/worker/worker.proto

package worker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecOutputChunk_Stream int32

const (
	ExecOutputChunk_STDOUT ExecOutputChunk_Stream = 0
	ExecOutputChunk_STDERR ExecOutputChunk_Stream = 1
)

// Enum value maps for ExecOutputChunk_Stream.
var (
	ExecOutputChunk_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecOutputChunk_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecOutputChunk_Stream) Enum() *ExecOutputChunk_Stream {
	p := new(ExecOutputChunk_Stream)
	*p = x
	return p
}

func (x ExecOutputChunk_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecOutputChunk_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_worker_proto_enumTypes[0].Descriptor()
}

func (ExecOutputChunk_Stream) Type() protoreflect.EnumType {
	return &file_proto_worker_worker_proto_enumTypes[0]
}

func (x ExecOutputChunk_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecOutputChunk_Stream.Descriptor instead.
func (ExecOutputChunk_Stream) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{10, 0}
}

type CreateSandboxRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Template       string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Timeout        int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Envs           map[string]string      `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MemoryMb       int32                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	CpuCount       int32                  `protobuf:"varint,5,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	NetworkEnabled bool                   `protobuf:"varint,6,opt,name=network_enabled,json=networkEnabled,proto3" json:"network_enabled,omitempty"`
	ImageRef       string                 `protobuf:"bytes,7,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Port           int32                  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"` // container port to expose via subdomain (default 80)
	// Sandbox snapshot template: if non-empty, boot from these S3 keys instead of base image.
	TemplateRootfsKey    string `protobuf:"bytes,9,opt,name=template_rootfs_key,json=templateRootfsKey,proto3" json:"template_rootfs_key,omitempty"`
	TemplateWorkspaceKey string `protobuf:"bytes,10,opt,name=template_workspace_key,json=templateWorkspaceKey,proto3" json:"template_workspace_key,omitempty"`
	// If set, attempt warm fork from local checkpoint snapshot (LoadSnapshot instead of cold boot).
	CheckpointId string `protobuf:"bytes,11,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	// Server-assigned sandbox ID. If non-empty, worker uses this instead of generating one.
	SandboxId string `protobuf:"bytes,12,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Egress allowlist: restrict outbound HTTPS to these hosts.
	// Supports exact ("api.anthropic.com") and wildcard ("*.openai.com") patterns.
	// Empty = all hosts allowed.
	EgressAllowlist []string `protobuf:"bytes,13,rep,name=egress_allowlist,json=egressAllowlist,proto3" json:"egress_allowlist,omitempty"`
	// Per-secret host restrictions: env var name → comma-separated allowed hosts.
	// Secrets are only substituted in requests to matching hosts.
	// Empty value or missing key = substitute on all allowed hosts.
	SecretAllowedHosts map[string]string `protobuf:"bytes,14,rep,name=secret_allowed_hosts,json=secretAllowedHosts,proto3" json:"secret_allowed_hosts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *CreateSandboxRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CreateSandboxRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *CreateSandboxRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateSandboxRequest) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *CreateSandboxRequest) GetNetworkEnabled() bool {
	if x != nil {
		return x.NetworkEnabled
	}
	return false
}

func (x *CreateSandboxRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *CreateSandboxRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateSandboxRequest) GetTemplateRootfsKey() string {
	if x != nil {
		return x.TemplateRootfsKey
	}
	return ""
}

func (x *CreateSandboxRequest) GetTemplateWorkspaceKey() string {
	if x != nil {
		return x.TemplateWorkspaceKey
	}
	return ""
}

func (x *CreateSandboxRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

func (x *CreateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxRequest) GetEgressAllowlist() []string {
	if x != nil {
		return x.EgressAllowlist
	}
	return nil
}

func (x *CreateSandboxRequest) GetSecretAllowedHosts() map[string]string {
	if x != nil {
		return x.SecretAllowedHosts
	}
	return nil
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DestroySandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySandboxRequest) Reset() {
	*x = DestroySandboxRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySandboxRequest) ProtoMessage() {}

func (x *DestroySandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySandboxRequest.ProtoReflect.Descriptor instead.
func (*DestroySandboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{2}
}

func (x *DestroySandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type DestroySandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySandboxResponse) Reset() {
	*x = DestroySandboxResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySandboxResponse) ProtoMessage() {}

func (x *DestroySandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySandboxResponse.ProtoReflect.Descriptor instead.
func (*DestroySandboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{3}
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{4}
}

func (x *GetSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Template      string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	StartedAt     int64                  `protobuf:"varint,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndAt         int64                  `protobuf:"varint,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{5}
}

func (x *GetSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *GetSandboxResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSandboxResponse) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *GetSandboxResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *GetSandboxResponse) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{6}
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*GetSandboxResponse  `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{7}
}

func (x *ListSandboxesResponse) GetSandboxes() []*GetSandboxResponse {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type ExecCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Envs          map[string]string      `protobuf:"bytes,4,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Timeout       int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandRequest) Reset() {
	*x = ExecCommandRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandRequest) ProtoMessage() {}

func (x *ExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{8}
}

func (x *ExecCommandRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecCommandRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ExecCommandRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecCommandRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ExecCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandResponse) Reset() {
	*x = ExecCommandResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandResponse) ProtoMessage() {}

func (x *ExecCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{9}
}

func (x *ExecCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type ExecOutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        ExecOutputChunk_Stream `protobuf:"varint,1,opt,name=stream,proto3,enum=worker.ExecOutputChunk_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutputChunk) Reset() {
	*x = ExecOutputChunk{}
	mi := &file_proto_worker_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutputChunk) ProtoMessage() {}

func (x *ExecOutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutputChunk.ProtoReflect.Descriptor instead.
func (*ExecOutputChunk) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{10}
}

func (x *ExecOutputChunk) GetStream() ExecOutputChunk_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecOutputChunk_STDOUT
}

func (x *ExecOutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{11}
}

func (x *ReadFileRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{12}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{13}
}

func (x *WriteFileRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{14}
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{15}
}

func (x *ListDirRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_proto_worker_worker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{16}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DirEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{17}
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreatePTYRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Shell         string                 `protobuf:"bytes,4,opt,name=shell,proto3" json:"shell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePTYRequest) Reset() {
	*x = CreatePTYRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePTYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePTYRequest) ProtoMessage() {}

func (x *CreatePTYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePTYRequest.ProtoReflect.Descriptor instead.
func (*CreatePTYRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePTYRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreatePTYRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CreatePTYRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CreatePTYRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type CreatePTYResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePTYResponse) Reset() {
	*x = CreatePTYResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePTYResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePTYResponse) ProtoMessage() {}

func (x *CreatePTYResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePTYResponse.ProtoReflect.Descriptor instead.
func (*CreatePTYResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{19}
}

func (x *CreatePTYResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PTYInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*PTYInput_Data
	//	*PTYInput_Resize
	Input         isPTYInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYInput) Reset() {
	*x = PTYInput{}
	mi := &file_proto_worker_worker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYInput) ProtoMessage() {}

func (x *PTYInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYInput.ProtoReflect.Descriptor instead.
func (*PTYInput) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{20}
}

func (x *PTYInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PTYInput) GetInput() isPTYInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *PTYInput) GetData() []byte {
	if x != nil {
		if x, ok := x.Input.(*PTYInput_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *PTYInput) GetResize() *PTYResize {
	if x != nil {
		if x, ok := x.Input.(*PTYInput_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isPTYInput_Input interface {
	isPTYInput_Input()
}

type PTYInput_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type PTYInput_Resize struct {
	Resize *PTYResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*PTYInput_Data) isPTYInput_Input() {}

func (*PTYInput_Resize) isPTYInput_Input() {}

type PTYResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYResize) Reset() {
	*x = PTYResize{}
	mi := &file_proto_worker_worker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYResize) ProtoMessage() {}

func (x *PTYResize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYResize.ProtoReflect.Descriptor instead.
func (*PTYResize) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{21}
}

func (x *PTYResize) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYResize) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PTYOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYOutput) Reset() {
	*x = PTYOutput{}
	mi := &file_proto_worker_worker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYOutput) ProtoMessage() {}

func (x *PTYOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYOutput.ProtoReflect.Descriptor instead.
func (*PTYOutput) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{22}
}

func (x *PTYOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PTYOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HibernateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HibernateSandboxRequest) Reset() {
	*x = HibernateSandboxRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HibernateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HibernateSandboxRequest) ProtoMessage() {}

func (x *HibernateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HibernateSandboxRequest.ProtoReflect.Descriptor instead.
func (*HibernateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{23}
}

func (x *HibernateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type HibernateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CheckpointKey string                 `protobuf:"bytes,2,opt,name=checkpoint_key,json=checkpointKey,proto3" json:"checkpoint_key,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HibernateSandboxResponse) Reset() {
	*x = HibernateSandboxResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HibernateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HibernateSandboxResponse) ProtoMessage() {}

func (x *HibernateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HibernateSandboxResponse.ProtoReflect.Descriptor instead.
func (*HibernateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{24}
}

func (x *HibernateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *HibernateSandboxResponse) GetCheckpointKey() string {
	if x != nil {
		return x.CheckpointKey
	}
	return ""
}

func (x *HibernateSandboxResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type WakeSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CheckpointKey string                 `protobuf:"bytes,2,opt,name=checkpoint_key,json=checkpointKey,proto3" json:"checkpoint_key,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeSandboxRequest) Reset() {
	*x = WakeSandboxRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeSandboxRequest) ProtoMessage() {}

func (x *WakeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeSandboxRequest.ProtoReflect.Descriptor instead.
func (*WakeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{25}
}

func (x *WakeSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *WakeSandboxRequest) GetCheckpointKey() string {
	if x != nil {
		return x.CheckpointKey
	}
	return ""
}

func (x *WakeSandboxRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type WakeSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeSandboxResponse) Reset() {
	*x = WakeSandboxResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeSandboxResponse) ProtoMessage() {}

func (x *WakeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeSandboxResponse.ProtoReflect.Descriptor instead.
func (*WakeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{26}
}

func (x *WakeSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *WakeSandboxResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SaveAsTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // UUID assigned by control plane
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAsTemplateRequest) Reset() {
	*x = SaveAsTemplateRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAsTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAsTemplateRequest) ProtoMessage() {}

func (x *SaveAsTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAsTemplateRequest.ProtoReflect.Descriptor instead.
func (*SaveAsTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{27}
}

func (x *SaveAsTemplateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *SaveAsTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type SaveAsTemplateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RootfsS3Key    string                 `protobuf:"bytes,1,opt,name=rootfs_s3_key,json=rootfsS3Key,proto3" json:"rootfs_s3_key,omitempty"`
	WorkspaceS3Key string                 `protobuf:"bytes,2,opt,name=workspace_s3_key,json=workspaceS3Key,proto3" json:"workspace_s3_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveAsTemplateResponse) Reset() {
	*x = SaveAsTemplateResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAsTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAsTemplateResponse) ProtoMessage() {}

func (x *SaveAsTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAsTemplateResponse.ProtoReflect.Descriptor instead.
func (*SaveAsTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{28}
}

func (x *SaveAsTemplateResponse) GetRootfsS3Key() string {
	if x != nil {
		return x.RootfsS3Key
	}
	return ""
}

func (x *SaveAsTemplateResponse) GetWorkspaceS3Key() string {
	if x != nil {
		return x.WorkspaceS3Key
	}
	return ""
}

type BuildTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dockerfile    string                 `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	EcrImageRef   string                 `protobuf:"bytes,4,opt,name=ecr_image_ref,json=ecrImageRef,proto3" json:"ecr_image_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTemplateRequest) Reset() {
	*x = BuildTemplateRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTemplateRequest) ProtoMessage() {}

func (x *BuildTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTemplateRequest.ProtoReflect.Descriptor instead.
func (*BuildTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{29}
}

func (x *BuildTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildTemplateRequest) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

func (x *BuildTemplateRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BuildTemplateRequest) GetEcrImageRef() string {
	if x != nil {
		return x.EcrImageRef
	}
	return ""
}

type BuildTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	BuildLog      string                 `protobuf:"bytes,2,opt,name=build_log,json=buildLog,proto3" json:"build_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTemplateResponse) Reset() {
	*x = BuildTemplateResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTemplateResponse) ProtoMessage() {}

func (x *BuildTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTemplateResponse.ProtoReflect.Descriptor instead.
func (*BuildTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{30}
}

func (x *BuildTemplateResponse) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *BuildTemplateResponse) GetBuildLog() string {
	if x != nil {
		return x.BuildLog
	}
	return ""
}

type ExecSessionCreateRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SandboxId             string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Command               string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args                  []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Envs                  map[string]string      `protobuf:"bytes,4,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd                   string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	TimeoutSeconds        int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	MaxRunAfterDisconnect int32                  `protobuf:"varint,7,opt,name=max_run_after_disconnect,json=maxRunAfterDisconnect,proto3" json:"max_run_after_disconnect,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExecSessionCreateRequest) Reset() {
	*x = ExecSessionCreateRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSessionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSessionCreateRequest) ProtoMessage() {}

func (x *ExecSessionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSessionCreateRequest.ProtoReflect.Descriptor instead.
func (*ExecSessionCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{31}
}

func (x *ExecSessionCreateRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecSessionCreateRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecSessionCreateRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecSessionCreateRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ExecSessionCreateRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecSessionCreateRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecSessionCreateRequest) GetMaxRunAfterDisconnect() int32 {
	if x != nil {
		return x.MaxRunAfterDisconnect
	}
	return 0
}

type ExecSessionCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSessionCreateResponse) Reset() {
	*x = ExecSessionCreateResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSessionCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSessionCreateResponse) ProtoMessage() {}

func (x *ExecSessionCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSessionCreateResponse.ProtoReflect.Descriptor instead.
func (*ExecSessionCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{32}
}

func (x *ExecSessionCreateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExecSessionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSessionListRequest) Reset() {
	*x = ExecSessionListRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSessionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSessionListRequest) ProtoMessage() {}

func (x *ExecSessionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSessionListRequest.ProtoReflect.Descriptor instead.
func (*ExecSessionListRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{33}
}

func (x *ExecSessionListRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type ExecSessionListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sessions      []*ExecSessionInfoEntry `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSessionListResponse) Reset() {
	*x = ExecSessionListResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSessionListResponse) ProtoMessage() {}

func (x *ExecSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSessionListResponse.ProtoReflect.Descriptor instead.
func (*ExecSessionListResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{34}
}

func (x *ExecSessionListResponse) GetSessions() []*ExecSessionInfoEntry {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type ExecSessionInfoEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command         string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args            []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Running         bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	ExitCode        int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartedAt       int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	AttachedClients int32                  `protobuf:"varint,7,opt,name=attached_clients,json=attachedClients,proto3" json:"attached_clients,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecSessionInfoEntry) Reset() {
	*x = ExecSessionInfoEntry{}
	mi := &file_proto_worker_worker_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSessionInfoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSessionInfoEntry) ProtoMessage() {}

func (x *ExecSessionInfoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSessionInfoEntry.ProtoReflect.Descriptor instead.
func (*ExecSessionInfoEntry) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{35}
}

func (x *ExecSessionInfoEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecSessionInfoEntry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecSessionInfoEntry) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecSessionInfoEntry) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ExecSessionInfoEntry) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecSessionInfoEntry) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ExecSessionInfoEntry) GetAttachedClients() int32 {
	if x != nil {
		return x.AttachedClients
	}
	return 0
}

type ExecSessionKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Signal        int32                  `protobuf:"varint,3,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSessionKillRequest) Reset() {
	*x = ExecSessionKillRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSessionKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSessionKillRequest) ProtoMessage() {}

func (x *ExecSessionKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSessionKillRequest.ProtoReflect.Descriptor instead.
func (*ExecSessionKillRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{36}
}

func (x *ExecSessionKillRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *ExecSessionKillRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecSessionKillRequest) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type ExecSessionKillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSessionKillResponse) Reset() {
	*x = ExecSessionKillResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSessionKillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSessionKillResponse) ProtoMessage() {}

func (x *ExecSessionKillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSessionKillResponse.ProtoReflect.Descriptor instead.
func (*ExecSessionKillResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{37}
}

type GetSandboxStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatsRequest) Reset() {
	*x = GetSandboxStatsRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatsRequest) ProtoMessage() {}

func (x *GetSandboxStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{38}
}

func (x *GetSandboxStatsRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type GetSandboxStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsage      uint64                 `protobuf:"varint,2,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	MemLimit      uint64                 `protobuf:"varint,3,opt,name=mem_limit,json=memLimit,proto3" json:"mem_limit,omitempty"`
	NetInput      uint64                 `protobuf:"varint,4,opt,name=net_input,json=netInput,proto3" json:"net_input,omitempty"`
	NetOutput     uint64                 `protobuf:"varint,5,opt,name=net_output,json=netOutput,proto3" json:"net_output,omitempty"`
	Pids          int32                  `protobuf:"varint,6,opt,name=pids,proto3" json:"pids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxStatsResponse) Reset() {
	*x = GetSandboxStatsResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxStatsResponse) ProtoMessage() {}

func (x *GetSandboxStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSandboxStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{39}
}

func (x *GetSandboxStatsResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *GetSandboxStatsResponse) GetMemUsage() uint64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *GetSandboxStatsResponse) GetMemLimit() uint64 {
	if x != nil {
		return x.MemLimit
	}
	return 0
}

func (x *GetSandboxStatsResponse) GetNetInput() uint64 {
	if x != nil {
		return x.NetInput
	}
	return 0
}

func (x *GetSandboxStatsResponse) GetNetOutput() uint64 {
	if x != nil {
		return x.NetOutput
	}
	return 0
}

func (x *GetSandboxStatsResponse) GetPids() int32 {
	if x != nil {
		return x.Pids
	}
	return 0
}

type CreateCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"` // UUID assigned by control plane
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckpointRequest) Reset() {
	*x = CreateCheckpointRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckpointRequest) ProtoMessage() {}

func (x *CreateCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckpointRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{40}
}

func (x *CreateCheckpointRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type CreateCheckpointResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RootfsS3Key    string                 `protobuf:"bytes,1,opt,name=rootfs_s3_key,json=rootfsS3Key,proto3" json:"rootfs_s3_key,omitempty"`
	WorkspaceS3Key string                 `protobuf:"bytes,2,opt,name=workspace_s3_key,json=workspaceS3Key,proto3" json:"workspace_s3_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCheckpointResponse) Reset() {
	*x = CreateCheckpointResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckpointResponse) ProtoMessage() {}

func (x *CreateCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckpointResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{41}
}

func (x *CreateCheckpointResponse) GetRootfsS3Key() string {
	if x != nil {
		return x.RootfsS3Key
	}
	return ""
}

func (x *CreateCheckpointResponse) GetWorkspaceS3Key() string {
	if x != nil {
		return x.WorkspaceS3Key
	}
	return ""
}

type RestoreCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxId     string                 `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCheckpointRequest) Reset() {
	*x = RestoreCheckpointRequest{}
	mi := &file_proto_worker_worker_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCheckpointRequest) ProtoMessage() {}

func (x *RestoreCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCheckpointRequest.ProtoReflect.Descriptor instead.
func (*RestoreCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{42}
}

func (x *RestoreCheckpointRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RestoreCheckpointRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type RestoreCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCheckpointResponse) Reset() {
	*x = RestoreCheckpointResponse{}
	mi := &file_proto_worker_worker_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCheckpointResponse) ProtoMessage() {}

func (x *RestoreCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_worker_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCheckpointResponse.ProtoReflect.Descriptor instead.
func (*RestoreCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_worker_proto_rawDescGZIP(), []int{43}
}

func (x *RestoreCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_worker_worker_proto protoreflect.FileDescriptor

const file_proto_worker_worker_proto_rawDesc = "" +
	"\n" +
	"\x19proto/worker/worker.proto\x12\x06worker\"\xd9\x05\n" +
	"\x14CreateSandboxRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12:\n" +
	"\x04envs\x18\x03 \x03(\v2&.worker.CreateSandboxRequest.EnvsEntryR\x04envs\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x05R\bmemoryMb\x12\x1b\n" +
	"\tcpu_count\x18\x05 \x01(\x05R\bcpuCount\x12'\n" +
	"\x0fnetwork_enabled\x18\x06 \x01(\bR\x0enetworkEnabled\x12\x1b\n" +
	"\timage_ref\x18\a \x01(\tR\bimageRef\x12\x12\n" +
	"\x04port\x18\b \x01(\x05R\x04port\x12.\n" +
	"\x13template_rootfs_key\x18\t \x01(\tR\x11templateRootfsKey\x124\n" +
	"\x16template_workspace_key\x18\n" +
	" \x01(\tR\x14templateWorkspaceKey\x12#\n" +
	"\rcheckpoint_id\x18\v \x01(\tR\fcheckpointId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\f \x01(\tR\tsandboxId\x12)\n" +
	"\x10egress_allowlist\x18\r \x03(\tR\x0fegressAllowlist\x12f\n" +
	"\x14secret_allowed_hosts\x18\x0e \x03(\v24.worker.CreateSandboxRequest.SecretAllowedHostsEntryR\x12secretAllowedHosts\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17SecretAllowedHostsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x15CreateSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"6\n" +
	"\x15DestroySandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x18\n" +
	"\x16DestroySandboxResponse\"2\n" +
	"\x11GetSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x9d\x01\n" +
	"\x12GetSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\x03R\tstartedAt\x12\x15\n" +
	"\x06end_at\x18\x05 \x01(\x03R\x05endAt\"\x16\n" +
	"\x14ListSandboxesRequest\"Q\n" +
	"\x15ListSandboxesResponse\x128\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x1a.worker.GetSandboxResponseR\tsandboxes\"\x80\x02\n" +
	"\x12ExecCommandRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x128\n" +
	"\x04envs\x18\x04 \x03(\v2$.worker.ExecCommandRequest.EnvsEntryR\x04envs\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x13ExecCommandResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"\x7f\n" +
	"\x0fExecOutputChunk\x126\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1e.worker.ExecOutputChunk.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"D\n" +
	"\x0fReadFileRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"_\n" +
	"\x10WriteFileRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\x13\n" +
	"\x11WriteFileResponse\"C\n" +
	"\x0eListDirRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"]\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"=\n" +
	"\x0fListDirResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.worker.DirEntryR\aentries\"o\n" +
	"\x10CreatePTYRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\x12\x14\n" +
	"\x05shell\x18\x04 \x01(\tR\x05shell\"2\n" +
	"\x11CreatePTYResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"u\n" +
	"\bPTYInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12+\n" +
	"\x06resize\x18\x03 \x01(\v2\x11.worker.PTYResizeH\x00R\x06resizeB\a\n" +
	"\x05input\"3\n" +
	"\tPTYResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\">\n" +
	"\tPTYOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"8\n" +
	"\x17HibernateSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\x7f\n" +
	"\x18HibernateSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0echeckpoint_key\x18\x02 \x01(\tR\rcheckpointKey\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"t\n" +
	"\x12WakeSandboxRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12%\n" +
	"\x0echeckpoint_key\x18\x02 \x01(\tR\rcheckpointKey\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"L\n" +
	"\x13WakeSandboxResponse\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"W\n" +
	"\x15SaveAsTemplateRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"f\n" +
	"\x16SaveAsTemplateResponse\x12\"\n" +
	"\rrootfs_s3_key\x18\x01 \x01(\tR\vrootfsS3Key\x12(\n" +
	"\x10workspace_s3_key\x18\x02 \x01(\tR\x0eworkspaceS3Key\"\x80\x01\n" +
	"\x14BuildTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tR\n" +
	"dockerfile\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\"\n" +
	"\recr_image_ref\x18\x04 \x01(\tR\vecrImageRef\"Q\n" +
	"\x15BuildTemplateResponse\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12\x1b\n" +
	"\tbuild_log\x18\x02 \x01(\tR\bbuildLog\"\xd4\x02\n" +
	"\x18ExecSessionCreateRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12>\n" +
	"\x04envs\x18\x04 \x03(\v2*.worker.ExecSessionCreateRequest.EnvsEntryR\x04envs\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x127\n" +
	"\x18max_run_after_disconnect\x18\a \x01(\x05R\x15maxRunAfterDisconnect\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x19ExecSessionCreateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"7\n" +
	"\x16ExecSessionListRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"S\n" +
	"\x17ExecSessionListResponse\x128\n" +
	"\bsessions\x18\x01 \x03(\v2\x1c.worker.ExecSessionInfoEntryR\bsessions\"\xe4\x01\n" +
	"\x14ExecSessionInfoEntry\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x18\n" +
	"\arunning\x18\x04 \x01(\bR\arunning\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12)\n" +
	"\x10attached_clients\x18\a \x01(\x05R\x0fattachedClients\"n\n" +
	"\x16ExecSessionKillRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\x05R\x06signal\"\x19\n" +
	"\x17ExecSessionKillResponse\"7\n" +
	"\x16GetSandboxStatsRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\"\xc4\x01\n" +
	"\x17GetSandboxStatsResponse\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_usage\x18\x02 \x01(\x04R\bmemUsage\x12\x1b\n" +
	"\tmem_limit\x18\x03 \x01(\x04R\bmemLimit\x12\x1b\n" +
	"\tnet_input\x18\x04 \x01(\x04R\bnetInput\x12\x1d\n" +
	"\n" +
	"net_output\x18\x05 \x01(\x04R\tnetOutput\x12\x12\n" +
	"\x04pids\x18\x06 \x01(\x05R\x04pids\"]\n" +
	"\x17CreateCheckpointRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\"h\n" +
	"\x18CreateCheckpointResponse\x12\"\n" +
	"\rrootfs_s3_key\x18\x01 \x01(\tR\vrootfsS3Key\x12(\n" +
	"\x10workspace_s3_key\x18\x02 \x01(\tR\x0eworkspaceS3Key\"^\n" +
	"\x18RestoreCheckpointRequest\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x01 \x01(\tR\tsandboxId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\tR\fcheckpointId\"5\n" +
	"\x19RestoreCheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcf\f\n" +
	"\rSandboxWorker\x12L\n" +
	"\rCreateSandbox\x12\x1c.worker.CreateSandboxRequest\x1a\x1d.worker.CreateSandboxResponse\x12O\n" +
	"\x0eDestroySandbox\x12\x1d.worker.DestroySandboxRequest\x1a\x1e.worker.DestroySandboxResponse\x12C\n" +
	"\n" +
	"GetSandbox\x12\x19.worker.GetSandboxRequest\x1a\x1a.worker.GetSandboxResponse\x12L\n" +
	"\rListSandboxes\x12\x1c.worker.ListSandboxesRequest\x1a\x1d.worker.ListSandboxesResponse\x12F\n" +
	"\vExecCommand\x12\x1a.worker.ExecCommandRequest\x1a\x1b.worker.ExecCommandResponse\x12J\n" +
	"\x11ExecCommandStream\x12\x1a.worker.ExecCommandRequest\x1a\x17.worker.ExecOutputChunk0\x01\x12=\n" +
	"\bReadFile\x12\x17.worker.ReadFileRequest\x1a\x18.worker.ReadFileResponse\x12@\n" +
	"\tWriteFile\x12\x18.worker.WriteFileRequest\x1a\x19.worker.WriteFileResponse\x12:\n" +
	"\aListDir\x12\x16.worker.ListDirRequest\x1a\x17.worker.ListDirResponse\x12@\n" +
	"\tCreatePTY\x12\x18.worker.CreatePTYRequest\x1a\x19.worker.CreatePTYResponse\x124\n" +
	"\tPTYStream\x12\x10.worker.PTYInput\x1a\x11.worker.PTYOutput(\x010\x01\x12X\n" +
	"\x11ExecSessionCreate\x12 .worker.ExecSessionCreateRequest\x1a!.worker.ExecSessionCreateResponse\x12R\n" +
	"\x0fExecSessionList\x12\x1e.worker.ExecSessionListRequest\x1a\x1f.worker.ExecSessionListResponse\x12R\n" +
	"\x0fExecSessionKill\x12\x1e.worker.ExecSessionKillRequest\x1a\x1f.worker.ExecSessionKillResponse\x12U\n" +
	"\x10HibernateSandbox\x12\x1f.worker.HibernateSandboxRequest\x1a .worker.HibernateSandboxResponse\x12F\n" +
	"\vWakeSandbox\x12\x1a.worker.WakeSandboxRequest\x1a\x1b.worker.WakeSandboxResponse\x12O\n" +
	"\x0eSaveAsTemplate\x12\x1d.worker.SaveAsTemplateRequest\x1a\x1e.worker.SaveAsTemplateResponse\x12U\n" +
	"\x10CreateCheckpoint\x12\x1f.worker.CreateCheckpointRequest\x1a .worker.CreateCheckpointResponse\x12X\n" +
	"\x11RestoreCheckpoint\x12 .worker.RestoreCheckpointRequest\x1a!.worker.RestoreCheckpointResponse\x12L\n" +
	"\rBuildTemplate\x12\x1c.worker.BuildTemplateRequest\x1a\x1d.worker.BuildTemplateResponse\x12R\n" +
	"\x0fGetSandboxStats\x12\x1e.worker.GetSandboxStatsRequest\x1a\x1f.worker.GetSandboxStatsResponseB1Z/github.com/opensandbox/opensandbox/proto/workerb\x06proto3"

var (
	file_proto_worker_worker_proto_rawDescOnce sync.Once
	file_proto_worker_worker_proto_rawDescData []byte
)

func file_proto_worker_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)))
	})
	return file_proto_worker_worker_proto_rawDescData
}

var file_proto_worker_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_worker_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_proto_worker_worker_proto_goTypes = []any{
	(ExecOutputChunk_Stream)(0),       // 0: worker.ExecOutputChunk.Stream
	(*CreateSandboxRequest)(nil),      // 1: worker.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),     // 2: worker.CreateSandboxResponse
	(*DestroySandboxRequest)(nil),     // 3: worker.DestroySandboxRequest
	(*DestroySandboxResponse)(nil),    // 4: worker.DestroySandboxResponse
	(*GetSandboxRequest)(nil),         // 5: worker.GetSandboxRequest
	(*GetSandboxResponse)(nil),        // 6: worker.GetSandboxResponse
	(*ListSandboxesRequest)(nil),      // 7: worker.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),     // 8: worker.ListSandboxesResponse
	(*ExecCommandRequest)(nil),        // 9: worker.ExecCommandRequest
	(*ExecCommandResponse)(nil),       // 10: worker.ExecCommandResponse
	(*ExecOutputChunk)(nil),           // 11: worker.ExecOutputChunk
	(*ReadFileRequest)(nil),           // 12: worker.ReadFileRequest
	(*ReadFileResponse)(nil),          // 13: worker.ReadFileResponse
	(*WriteFileRequest)(nil),          // 14: worker.WriteFileRequest
	(*WriteFileResponse)(nil),         // 15: worker.WriteFileResponse
	(*ListDirRequest)(nil),            // 16: worker.ListDirRequest
	(*DirEntry)(nil),                  // 17: worker.DirEntry
	(*ListDirResponse)(nil),           // 18: worker.ListDirResponse
	(*CreatePTYRequest)(nil),          // 19: worker.CreatePTYRequest
	(*CreatePTYResponse)(nil),         // 20: worker.CreatePTYResponse
	(*PTYInput)(nil),                  // 21: worker.PTYInput
	(*PTYResize)(nil),                 // 22: worker.PTYResize
	(*PTYOutput)(nil),                 // 23: worker.PTYOutput
	(*HibernateSandboxRequest)(nil),   // 24: worker.HibernateSandboxRequest
	(*HibernateSandboxResponse)(nil),  // 25: worker.HibernateSandboxResponse
	(*WakeSandboxRequest)(nil),        // 26: worker.WakeSandboxRequest
	(*WakeSandboxResponse)(nil),       // 27: worker.WakeSandboxResponse
	(*SaveAsTemplateRequest)(nil),     // 28: worker.SaveAsTemplateRequest
	(*SaveAsTemplateResponse)(nil),    // 29: worker.SaveAsTemplateResponse
	(*BuildTemplateRequest)(nil),      // 30: worker.BuildTemplateRequest
	(*BuildTemplateResponse)(nil),     // 31: worker.BuildTemplateResponse
	(*ExecSessionCreateRequest)(nil),  // 32: worker.ExecSessionCreateRequest
	(*ExecSessionCreateResponse)(nil), // 33: worker.ExecSessionCreateResponse
	(*ExecSessionListRequest)(nil),    // 34: worker.ExecSessionListRequest
	(*ExecSessionListResponse)(nil),   // 35: worker.ExecSessionListResponse
	(*ExecSessionInfoEntry)(nil),      // 36: worker.ExecSessionInfoEntry
	(*ExecSessionKillRequest)(nil),    // 37: worker.ExecSessionKillRequest
	(*ExecSessionKillResponse)(nil),   // 38: worker.ExecSessionKillResponse
	(*GetSandboxStatsRequest)(nil),    // 39: worker.GetSandboxStatsRequest
	(*GetSandboxStatsResponse)(nil),   // 40: worker.GetSandboxStatsResponse
	(*CreateCheckpointRequest)(nil),   // 41: worker.CreateCheckpointRequest
	(*CreateCheckpointResponse)(nil),  // 42: worker.CreateCheckpointResponse
	(*RestoreCheckpointRequest)(nil),  // 43: worker.RestoreCheckpointRequest
	(*RestoreCheckpointResponse)(nil), // 44: worker.RestoreCheckpointResponse
	nil,                               // 45: worker.CreateSandboxRequest.EnvsEntry
	nil,                               // 46: worker.CreateSandboxRequest.SecretAllowedHostsEntry
	nil,                               // 47: worker.ExecCommandRequest.EnvsEntry
	nil,                               // 48: worker.ExecSessionCreateRequest.EnvsEntry
}
var file_proto_worker_worker_proto_depIdxs = []int32{
	45, // 0: worker.CreateSandboxRequest.envs:type_name -> worker.CreateSandboxRequest.EnvsEntry
	46, // 1: worker.CreateSandboxRequest.secret_allowed_hosts:type_name -> worker.CreateSandboxRequest.SecretAllowedHostsEntry
	6,  // 2: worker.ListSandboxesResponse.sandboxes:type_name -> worker.GetSandboxResponse
	47, // 3: worker.ExecCommandRequest.envs:type_name -> worker.ExecCommandRequest.EnvsEntry
	0,  // 4: worker.ExecOutputChunk.stream:type_name -> worker.ExecOutputChunk.Stream
	17, // 5: worker.ListDirResponse.entries:type_name -> worker.DirEntry
	22, // 6: worker.PTYInput.resize:type_name -> worker.PTYResize
	48, // 7: worker.ExecSessionCreateRequest.envs:type_name -> worker.ExecSessionCreateRequest.EnvsEntry
	36, // 8: worker.ExecSessionListResponse.sessions:type_name -> worker.ExecSessionInfoEntry
	1,  // 9: worker.SandboxWorker.CreateSandbox:input_type -> worker.CreateSandboxRequest
	3,  // 10: worker.SandboxWorker.DestroySandbox:input_type -> worker.DestroySandboxRequest
	5,  // 11: worker.SandboxWorker.GetSandbox:input_type -> worker.GetSandboxRequest
	7,  // 12: worker.SandboxWorker.ListSandboxes:input_type -> worker.ListSandboxesRequest
	9,  // 13: worker.SandboxWorker.ExecCommand:input_type -> worker.ExecCommandRequest
	9,  // 14: worker.SandboxWorker.ExecCommandStream:input_type -> worker.ExecCommandRequest
	12, // 15: worker.SandboxWorker.ReadFile:input_type -> worker.ReadFileRequest
	14, // 16: worker.SandboxWorker.WriteFile:input_type -> worker.WriteFileRequest
	16, // 17: worker.SandboxWorker.ListDir:input_type -> worker.ListDirRequest
	19, // 18: worker.SandboxWorker.CreatePTY:input_type -> worker.CreatePTYRequest
	21, // 19: worker.SandboxWorker.PTYStream:input_type -> worker.PTYInput
	32, // 20: worker.SandboxWorker.ExecSessionCreate:input_type -> worker.ExecSessionCreateRequest
	34, // 21: worker.SandboxWorker.ExecSessionList:input_type -> worker.ExecSessionListRequest
	37, // 22: worker.SandboxWorker.ExecSessionKill:input_type -> worker.ExecSessionKillRequest
	24, // 23: worker.SandboxWorker.HibernateSandbox:input_type -> worker.HibernateSandboxRequest
	26, // 24: worker.SandboxWorker.WakeSandbox:input_type -> worker.WakeSandboxRequest
	28, // 25: worker.SandboxWorker.SaveAsTemplate:input_type -> worker.SaveAsTemplateRequest
	41, // 26: worker.SandboxWorker.CreateCheckpoint:input_type -> worker.CreateCheckpointRequest
	43, // 27: worker.SandboxWorker.RestoreCheckpoint:input_type -> worker.RestoreCheckpointRequest
	30, // 28: worker.SandboxWorker.BuildTemplate:input_type -> worker.BuildTemplateRequest
	39, // 29: worker.SandboxWorker.GetSandboxStats:input_type -> worker.GetSandboxStatsRequest
	2,  // 30: worker.SandboxWorker.CreateSandbox:output_type -> worker.CreateSandboxResponse
	4,  // 31: worker.SandboxWorker.DestroySandbox:output_type -> worker.DestroySandboxResponse
	6,  // 32: worker.SandboxWorker.GetSandbox:output_type -> worker.GetSandboxResponse
	8,  // 33: worker.SandboxWorker.ListSandboxes:output_type -> worker.ListSandboxesResponse
	10, // 34: worker.SandboxWorker.ExecCommand:output_type -> worker.ExecCommandResponse
	11, // 35: worker.SandboxWorker.ExecCommandStream:output_type -> worker.ExecOutputChunk
	13, // 36: worker.SandboxWorker.ReadFile:output_type -> worker.ReadFileResponse
	15, // 37: worker.SandboxWorker.WriteFile:output_type -> worker.WriteFileResponse
	18, // 38: worker.SandboxWorker.ListDir:output_type -> worker.ListDirResponse
	20, // 39: worker.SandboxWorker.CreatePTY:output_type -> worker.CreatePTYResponse
	23, // 40: worker.SandboxWorker.PTYStream:output_type -> worker.PTYOutput
	33, // 41: worker.SandboxWorker.ExecSessionCreate:output_type -> worker.ExecSessionCreateResponse
	35, // 42: worker.SandboxWorker.ExecSessionList:output_type -> worker.ExecSessionListResponse
	38, // 43: worker.SandboxWorker.ExecSessionKill:output_type -> worker.ExecSessionKillResponse
	25, // 44: worker.SandboxWorker.HibernateSandbox:output_type -> worker.HibernateSandboxResponse
	27, // 45: worker.SandboxWorker.WakeSandbox:output_type -> worker.WakeSandboxResponse
	29, // 46: worker.SandboxWorker.SaveAsTemplate:output_type -> worker.SaveAsTemplateResponse
	42, // 47: worker.SandboxWorker.CreateCheckpoint:output_type -> worker.CreateCheckpointResponse
	44, // 48: worker.SandboxWorker.RestoreCheckpoint:output_type -> worker.RestoreCheckpointResponse
	31, // 49: worker.SandboxWorker.BuildTemplate:output_type -> worker.BuildTemplateResponse
	40, // 50: worker.SandboxWorker.GetSandboxStats:output_type -> worker.GetSandboxStatsResponse
	30, // [30:51] is the sub-list for method output_type
	9,  // [9:30] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_worker_worker_proto_init() }
func file_proto_worker_worker_proto_init() {
	if File_proto_worker_worker_proto != nil {
		return
	}
	file_proto_worker_worker_proto_msgTypes[20].OneofWrappers = []any{
		(*PTYInput_Data)(nil),
		(*PTYInput_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_worker_proto_rawDesc), len(file_proto_worker_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_worker_proto_depIdxs,
		EnumInfos:         file_proto_worker_worker_proto_enumTypes,
		MessageInfos:      file_proto_worker_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_worker_proto = out.File
	file_proto_worker_worker_proto_goTypes = nil
	file_proto_worker_worker_proto_depIdxs = nil
}
