// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecOutputChunk_Stream int32

const (
	ExecOutputChunk_STDOUT ExecOutputChunk_Stream = 0
	ExecOutputChunk_STDERR ExecOutputChunk_Stream = 1
)

// Enum value maps for ExecOutputChunk_Stream.
var (
	ExecOutputChunk_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecOutputChunk_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecOutputChunk_Stream) Enum() *ExecOutputChunk_Stream {
	p := new(ExecOutputChunk_Stream)
	*p = x
	return p
}

func (x ExecOutputChunk_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecOutputChunk_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[0].Descriptor()
}

func (ExecOutputChunk_Stream) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[0]
}

func (x ExecOutputChunk_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecOutputChunk_Stream.Descriptor instead.
func (ExecOutputChunk_Stream) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2, 0}
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Envs           map[string]string      `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd            string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 = default (60s)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecRequest) GetEnvs() map[string]string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type ExecOutputChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        ExecOutputChunk_Stream `protobuf:"varint,1,opt,name=stream,proto3,enum=agent.ExecOutputChunk_Stream" json:"stream,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutputChunk) Reset() {
	*x = ExecOutputChunk{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutputChunk) ProtoMessage() {}

func (x *ExecOutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutputChunk.ProtoReflect.Descriptor instead.
func (*ExecOutputChunk) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecOutputChunk) GetStream() ExecOutputChunk_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecOutputChunk_STDOUT
}

func (x *ExecOutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"` // file mode (0 = default 0644)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DirEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MakeDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeDirRequest) Reset() {
	*x = MakeDirRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirRequest) ProtoMessage() {}

func (x *MakeDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirRequest.ProtoReflect.Descriptor instead.
func (*MakeDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *MakeDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MakeDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeDirResponse) Reset() {
	*x = MakeDirResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeDirResponse) ProtoMessage() {}

func (x *MakeDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeDirResponse.ProtoReflect.Descriptor instead.
func (*MakeDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ExistsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       string                 `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *StatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StatResponse) GetModTime() string {
	if x != nil {
		return x.ModTime
	}
	return ""
}

func (x *StatResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsage      uint64                 `protobuf:"varint,2,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`    // bytes
	MemLimit      uint64                 `protobuf:"varint,3,opt,name=mem_limit,json=memLimit,proto3" json:"mem_limit,omitempty"`    // bytes
	NetInput      uint64                 `protobuf:"varint,4,opt,name=net_input,json=netInput,proto3" json:"net_input,omitempty"`    // bytes
	NetOutput     uint64                 `protobuf:"varint,5,opt,name=net_output,json=netOutput,proto3" json:"net_output,omitempty"` // bytes
	Pids          int32                  `protobuf:"varint,6,opt,name=pids,proto3" json:"pids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *StatsResponse) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *StatsResponse) GetMemUsage() uint64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *StatsResponse) GetMemLimit() uint64 {
	if x != nil {
		return x.MemLimit
	}
	return 0
}

func (x *StatsResponse) GetNetInput() uint64 {
	if x != nil {
		return x.NetInput
	}
	return 0
}

func (x *StatsResponse) GetNetOutput() uint64 {
	if x != nil {
		return x.NetOutput
	}
	return 0
}

func (x *StatsResponse) GetPids() int32 {
	if x != nil {
		return x.Pids
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{20}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type PTYCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          int32                  `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Shell         string                 `protobuf:"bytes,3,opt,name=shell,proto3" json:"shell,omitempty"` // e.g., "/bin/bash" (empty = default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYCreateRequest) Reset() {
	*x = PTYCreateRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYCreateRequest) ProtoMessage() {}

func (x *PTYCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYCreateRequest.ProtoReflect.Descriptor instead.
func (*PTYCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *PTYCreateRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYCreateRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *PTYCreateRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type PTYCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DataPort      uint32                 `protobuf:"varint,2,opt,name=data_port,json=dataPort,proto3" json:"data_port,omitempty"` // vsock port for raw PTY I/O stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYCreateResponse) Reset() {
	*x = PTYCreateResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYCreateResponse) ProtoMessage() {}

func (x *PTYCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYCreateResponse.ProtoReflect.Descriptor instead.
func (*PTYCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{23}
}

func (x *PTYCreateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PTYCreateResponse) GetDataPort() uint32 {
	if x != nil {
		return x.DataPort
	}
	return 0
}

type PTYResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          int32                  `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          int32                  `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYResizeRequest) Reset() {
	*x = PTYResizeRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYResizeRequest) ProtoMessage() {}

func (x *PTYResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYResizeRequest.ProtoReflect.Descriptor instead.
func (*PTYResizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *PTYResizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PTYResizeRequest) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PTYResizeRequest) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PTYResizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYResizeResponse) Reset() {
	*x = PTYResizeResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYResizeResponse) ProtoMessage() {}

func (x *PTYResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYResizeResponse.ProtoReflect.Descriptor instead.
func (*PTYResizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{25}
}

type PTYKillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYKillRequest) Reset() {
	*x = PTYKillRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYKillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYKillRequest) ProtoMessage() {}

func (x *PTYKillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYKillRequest.ProtoReflect.Descriptor instead.
func (*PTYKillRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{26}
}

func (x *PTYKillRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PTYKillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTYKillResponse) Reset() {
	*x = PTYKillResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTYKillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTYKillResponse) ProtoMessage() {}

func (x *PTYKillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTYKillResponse.ProtoReflect.Descriptor instead.
func (*PTYKillResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{27}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{28}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{29}
}

type SyncFSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFSRequest) Reset() {
	*x = SyncFSRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFSRequest) ProtoMessage() {}

func (x *SyncFSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFSRequest.ProtoReflect.Descriptor instead.
func (*SyncFSRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{30}
}

type SyncFSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFSResponse) Reset() {
	*x = SyncFSResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFSResponse) ProtoMessage() {}

func (x *SyncFSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFSResponse.ProtoReflect.Descriptor instead.
func (*SyncFSResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{31}
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\"\xe1\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x120\n" +
	"\x04envs\x18\x03 \x03(\v2\x1c.agent.ExecRequest.EnvsEntryR\x04envs\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a7\n" +
	"\tEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"~\n" +
	"\x0fExecOutputChunk\x125\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1d.agent.ExecOutputChunk.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"T\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"\x13\n" +
	"\x11WriteFileResponse\"$\n" +
	"\x0eListDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"]\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"<\n" +
	"\x0fListDirResponse\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.agent.DirEntryR\aentries\"$\n" +
	"\x0eMakeDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x11\n" +
	"\x0fMakeDirResponse\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x10\n" +
	"\x0eRemoveResponse\"#\n" +
	"\rExistsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x90\x01\n" +
	"\fStatResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\tR\amodTime\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\"\x0e\n" +
	"\fStatsRequest\"\xba\x01\n" +
	"\rStatsResponse\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tmem_usage\x18\x02 \x01(\x04R\bmemUsage\x12\x1b\n" +
	"\tmem_limit\x18\x03 \x01(\x04R\bmemLimit\x12\x1b\n" +
	"\tnet_input\x18\x04 \x01(\x04R\bnetInput\x12\x1d\n" +
	"\n" +
	"net_output\x18\x05 \x01(\x04R\tnetOutput\x12\x12\n" +
	"\x04pids\x18\x06 \x01(\x05R\x04pids\"\r\n" +
	"\vPingRequest\"O\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\"P\n" +
	"\x10PTYCreateRequest\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\x12\x14\n" +
	"\x05shell\x18\x03 \x01(\tR\x05shell\"O\n" +
	"\x11PTYCreateResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tdata_port\x18\x02 \x01(\rR\bdataPort\"Y\n" +
	"\x10PTYResizeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\x05R\x04rows\"\x13\n" +
	"\x11PTYResizeResponse\"/\n" +
	"\x0ePTYKillRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x11\n" +
	"\x0fPTYKillResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x0f\n" +
	"\rSyncFSRequest\"\x10\n" +
	"\x0eSyncFSResponse2\x9e\a\n" +
	"\fSandboxAgent\x12/\n" +
	"\x04Exec\x12\x12.agent.ExecRequest\x1a\x13.agent.ExecResponse\x12:\n" +
	"\n" +
	"ExecStream\x12\x12.agent.ExecRequest\x1a\x16.agent.ExecOutputChunk0\x01\x12;\n" +
	"\bReadFile\x12\x16.agent.ReadFileRequest\x1a\x17.agent.ReadFileResponse\x12>\n" +
	"\tWriteFile\x12\x17.agent.WriteFileRequest\x1a\x18.agent.WriteFileResponse\x128\n" +
	"\aListDir\x12\x15.agent.ListDirRequest\x1a\x16.agent.ListDirResponse\x128\n" +
	"\aMakeDir\x12\x15.agent.MakeDirRequest\x1a\x16.agent.MakeDirResponse\x125\n" +
	"\x06Remove\x12\x14.agent.RemoveRequest\x1a\x15.agent.RemoveResponse\x125\n" +
	"\x06Exists\x12\x14.agent.ExistsRequest\x1a\x15.agent.ExistsResponse\x12/\n" +
	"\x04Stat\x12\x12.agent.StatRequest\x1a\x13.agent.StatResponse\x122\n" +
	"\x05Stats\x12\x13.agent.StatsRequest\x1a\x14.agent.StatsResponse\x12/\n" +
	"\x04Ping\x12\x12.agent.PingRequest\x1a\x13.agent.PingResponse\x12>\n" +
	"\tPTYCreate\x12\x17.agent.PTYCreateRequest\x1a\x18.agent.PTYCreateResponse\x12>\n" +
	"\tPTYResize\x12\x17.agent.PTYResizeRequest\x1a\x18.agent.PTYResizeResponse\x128\n" +
	"\aPTYKill\x12\x15.agent.PTYKillRequest\x1a\x16.agent.PTYKillResponse\x12;\n" +
	"\bShutdown\x12\x16.agent.ShutdownRequest\x1a\x17.agent.ShutdownResponse\x125\n" +
	"\x06SyncFS\x12\x14.agent.SyncFSRequest\x1a\x15.agent.SyncFSResponseB0Z.github.com/opensandbox/opensandbox/proto/agentb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_agent_agent_proto_goTypes = []any{
	(ExecOutputChunk_Stream)(0), // 0: agent.ExecOutputChunk.Stream
	(*ExecRequest)(nil),         // 1: agent.ExecRequest
	(*ExecResponse)(nil),        // 2: agent.ExecResponse
	(*ExecOutputChunk)(nil),     // 3: agent.ExecOutputChunk
	(*ReadFileRequest)(nil),     // 4: agent.ReadFileRequest
	(*ReadFileResponse)(nil),    // 5: agent.ReadFileResponse
	(*WriteFileRequest)(nil),    // 6: agent.WriteFileRequest
	(*WriteFileResponse)(nil),   // 7: agent.WriteFileResponse
	(*ListDirRequest)(nil),      // 8: agent.ListDirRequest
	(*DirEntry)(nil),            // 9: agent.DirEntry
	(*ListDirResponse)(nil),     // 10: agent.ListDirResponse
	(*MakeDirRequest)(nil),      // 11: agent.MakeDirRequest
	(*MakeDirResponse)(nil),     // 12: agent.MakeDirResponse
	(*RemoveRequest)(nil),       // 13: agent.RemoveRequest
	(*RemoveResponse)(nil),      // 14: agent.RemoveResponse
	(*ExistsRequest)(nil),       // 15: agent.ExistsRequest
	(*ExistsResponse)(nil),      // 16: agent.ExistsResponse
	(*StatRequest)(nil),         // 17: agent.StatRequest
	(*StatResponse)(nil),        // 18: agent.StatResponse
	(*StatsRequest)(nil),        // 19: agent.StatsRequest
	(*StatsResponse)(nil),       // 20: agent.StatsResponse
	(*PingRequest)(nil),         // 21: agent.PingRequest
	(*PingResponse)(nil),        // 22: agent.PingResponse
	(*PTYCreateRequest)(nil),    // 23: agent.PTYCreateRequest
	(*PTYCreateResponse)(nil),   // 24: agent.PTYCreateResponse
	(*PTYResizeRequest)(nil),    // 25: agent.PTYResizeRequest
	(*PTYResizeResponse)(nil),   // 26: agent.PTYResizeResponse
	(*PTYKillRequest)(nil),      // 27: agent.PTYKillRequest
	(*PTYKillResponse)(nil),     // 28: agent.PTYKillResponse
	(*ShutdownRequest)(nil),     // 29: agent.ShutdownRequest
	(*ShutdownResponse)(nil),    // 30: agent.ShutdownResponse
	(*SyncFSRequest)(nil),       // 31: agent.SyncFSRequest
	(*SyncFSResponse)(nil),      // 32: agent.SyncFSResponse
	nil,                         // 33: agent.ExecRequest.EnvsEntry
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	33, // 0: agent.ExecRequest.envs:type_name -> agent.ExecRequest.EnvsEntry
	0,  // 1: agent.ExecOutputChunk.stream:type_name -> agent.ExecOutputChunk.Stream
	9,  // 2: agent.ListDirResponse.entries:type_name -> agent.DirEntry
	1,  // 3: agent.SandboxAgent.Exec:input_type -> agent.ExecRequest
	1,  // 4: agent.SandboxAgent.ExecStream:input_type -> agent.ExecRequest
	4,  // 5: agent.SandboxAgent.ReadFile:input_type -> agent.ReadFileRequest
	6,  // 6: agent.SandboxAgent.WriteFile:input_type -> agent.WriteFileRequest
	8,  // 7: agent.SandboxAgent.ListDir:input_type -> agent.ListDirRequest
	11, // 8: agent.SandboxAgent.MakeDir:input_type -> agent.MakeDirRequest
	13, // 9: agent.SandboxAgent.Remove:input_type -> agent.RemoveRequest
	15, // 10: agent.SandboxAgent.Exists:input_type -> agent.ExistsRequest
	17, // 11: agent.SandboxAgent.Stat:input_type -> agent.StatRequest
	19, // 12: agent.SandboxAgent.Stats:input_type -> agent.StatsRequest
	21, // 13: agent.SandboxAgent.Ping:input_type -> agent.PingRequest
	23, // 14: agent.SandboxAgent.PTYCreate:input_type -> agent.PTYCreateRequest
	25, // 15: agent.SandboxAgent.PTYResize:input_type -> agent.PTYResizeRequest
	27, // 16: agent.SandboxAgent.PTYKill:input_type -> agent.PTYKillRequest
	29, // 17: agent.SandboxAgent.Shutdown:input_type -> agent.ShutdownRequest
	31, // 18: agent.SandboxAgent.SyncFS:input_type -> agent.SyncFSRequest
	2,  // 19: agent.SandboxAgent.Exec:output_type -> agent.ExecResponse
	3,  // 20: agent.SandboxAgent.ExecStream:output_type -> agent.ExecOutputChunk
	5,  // 21: agent.SandboxAgent.ReadFile:output_type -> agent.ReadFileResponse
	7,  // 22: agent.SandboxAgent.WriteFile:output_type -> agent.WriteFileResponse
	10, // 23: agent.SandboxAgent.ListDir:output_type -> agent.ListDirResponse
	12, // 24: agent.SandboxAgent.MakeDir:output_type -> agent.MakeDirResponse
	14, // 25: agent.SandboxAgent.Remove:output_type -> agent.RemoveResponse
	16, // 26: agent.SandboxAgent.Exists:output_type -> agent.ExistsResponse
	18, // 27: agent.SandboxAgent.Stat:output_type -> agent.StatResponse
	20, // 28: agent.SandboxAgent.Stats:output_type -> agent.StatsResponse
	22, // 29: agent.SandboxAgent.Ping:output_type -> agent.PingResponse
	24, // 30: agent.SandboxAgent.PTYCreate:output_type -> agent.PTYCreateResponse
	26, // 31: agent.SandboxAgent.PTYResize:output_type -> agent.PTYResizeResponse
	28, // 32: agent.SandboxAgent.PTYKill:output_type -> agent.PTYKillResponse
	30, // 33: agent.SandboxAgent.Shutdown:output_type -> agent.ShutdownResponse
	32, // 34: agent.SandboxAgent.SyncFS:output_type -> agent.SyncFSResponse
	19, // [19:35] is the sub-list for method output_type
	3,  // [3:19] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
