// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxAgent_Exec_FullMethodName       = "/agent.SandboxAgent/Exec"
	SandboxAgent_ExecStream_FullMethodName = "/agent.SandboxAgent/ExecStream"
	SandboxAgent_ReadFile_FullMethodName   = "/agent.SandboxAgent/ReadFile"
	SandboxAgent_WriteFile_FullMethodName  = "/agent.SandboxAgent/WriteFile"
	SandboxAgent_ListDir_FullMethodName    = "/agent.SandboxAgent/ListDir"
	SandboxAgent_MakeDir_FullMethodName    = "/agent.SandboxAgent/MakeDir"
	SandboxAgent_Remove_FullMethodName     = "/agent.SandboxAgent/Remove"
	SandboxAgent_Exists_FullMethodName     = "/agent.SandboxAgent/Exists"
	SandboxAgent_Stat_FullMethodName       = "/agent.SandboxAgent/Stat"
	SandboxAgent_Stats_FullMethodName      = "/agent.SandboxAgent/Stats"
	SandboxAgent_Ping_FullMethodName       = "/agent.SandboxAgent/Ping"
	SandboxAgent_PTYCreate_FullMethodName  = "/agent.SandboxAgent/PTYCreate"
	SandboxAgent_PTYResize_FullMethodName  = "/agent.SandboxAgent/PTYResize"
	SandboxAgent_PTYKill_FullMethodName    = "/agent.SandboxAgent/PTYKill"
	SandboxAgent_Shutdown_FullMethodName   = "/agent.SandboxAgent/Shutdown"
	SandboxAgent_SyncFS_FullMethodName     = "/agent.SandboxAgent/SyncFS"
)

// SandboxAgentClient is the client API for SandboxAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxAgent runs inside each Firecracker microVM and handles
// exec, file ops, PTY, and stats over gRPC via vsock.
type SandboxAgentClient interface {
	// Exec runs a command and returns the result after completion.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// ExecStream runs a command and streams stdout/stderr chunks in real time.
	ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutputChunk], error)
	// Filesystem operations
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Stats returns live resource usage from /proc.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Ping verifies the agent is responsive.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// PTY management (data flows over a separate vsock port per session)
	PTYCreate(ctx context.Context, in *PTYCreateRequest, opts ...grpc.CallOption) (*PTYCreateResponse, error)
	PTYResize(ctx context.Context, in *PTYResizeRequest, opts ...grpc.CallOption) (*PTYResizeResponse, error)
	PTYKill(ctx context.Context, in *PTYKillRequest, opts ...grpc.CallOption) (*PTYKillResponse, error)
	// Shutdown gracefully terminates the agent and syncs disks.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// SyncFS flushes all filesystem buffers without exiting.
	// Used before snapshot to ensure disk state is consistent.
	SyncFS(ctx context.Context, in *SyncFSRequest, opts ...grpc.CallOption) (*SyncFSResponse, error)
}

type sandboxAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxAgentClient(cc grpc.ClientConnInterface) SandboxAgentClient {
	return &sandboxAgentClient{cc}
}

func (c *sandboxAgentClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[0], SandboxAgent_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ExecStreamClient = grpc.ServerStreamingClient[ExecOutputChunk]

func (c *sandboxAgentClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeDirResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_MakeDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PTYCreate(ctx context.Context, in *PTYCreateRequest, opts ...grpc.CallOption) (*PTYCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PTYCreateResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_PTYCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PTYResize(ctx context.Context, in *PTYResizeRequest, opts ...grpc.CallOption) (*PTYResizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PTYResizeResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_PTYResize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PTYKill(ctx context.Context, in *PTYKillRequest, opts ...grpc.CallOption) (*PTYKillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PTYKillResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_PTYKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SyncFS(ctx context.Context, in *SyncFSRequest, opts ...grpc.CallOption) (*SyncFSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncFSResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_SyncFS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxAgentServer is the server API for SandboxAgent service.
// All implementations must embed UnimplementedSandboxAgentServer
// for forward compatibility.
//
// SandboxAgent runs inside each Firecracker microVM and handles
// exec, file ops, PTY, and stats over gRPC via vsock.
type SandboxAgentServer interface {
	// Exec runs a command and returns the result after completion.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// ExecStream runs a command and streams stdout/stderr chunks in real time.
	ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecOutputChunk]) error
	// Filesystem operations
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// Stats returns live resource usage from /proc.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Ping verifies the agent is responsive.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// PTY management (data flows over a separate vsock port per session)
	PTYCreate(context.Context, *PTYCreateRequest) (*PTYCreateResponse, error)
	PTYResize(context.Context, *PTYResizeRequest) (*PTYResizeResponse, error)
	PTYKill(context.Context, *PTYKillRequest) (*PTYKillResponse, error)
	// Shutdown gracefully terminates the agent and syncs disks.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// SyncFS flushes all filesystem buffers without exiting.
	// Used before snapshot to ensure disk state is consistent.
	SyncFS(context.Context, *SyncFSRequest) (*SyncFSResponse, error)
	mustEmbedUnimplementedSandboxAgentServer()
}

// UnimplementedSandboxAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxAgentServer struct{}

func (UnimplementedSandboxAgentServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxAgentServer) ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedSandboxAgentServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxAgentServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxAgentServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedSandboxAgentServer) MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeDir not implemented")
}
func (UnimplementedSandboxAgentServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedSandboxAgentServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedSandboxAgentServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedSandboxAgentServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedSandboxAgentServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSandboxAgentServer) PTYCreate(context.Context, *PTYCreateRequest) (*PTYCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PTYCreate not implemented")
}
func (UnimplementedSandboxAgentServer) PTYResize(context.Context, *PTYResizeRequest) (*PTYResizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PTYResize not implemented")
}
func (UnimplementedSandboxAgentServer) PTYKill(context.Context, *PTYKillRequest) (*PTYKillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PTYKill not implemented")
}
func (UnimplementedSandboxAgentServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedSandboxAgentServer) SyncFS(context.Context, *SyncFSRequest) (*SyncFSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncFS not implemented")
}
func (UnimplementedSandboxAgentServer) mustEmbedUnimplementedSandboxAgentServer() {}
func (UnimplementedSandboxAgentServer) testEmbeddedByValue()                      {}

// UnsafeSandboxAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxAgentServer will
// result in compilation errors.
type UnsafeSandboxAgentServer interface {
	mustEmbedUnimplementedSandboxAgentServer()
}

func RegisterSandboxAgentServer(s grpc.ServiceRegistrar, srv SandboxAgentServer) {
	// If the following call panics, it indicates UnimplementedSandboxAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxAgent_ServiceDesc, srv)
}

func _SandboxAgent_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxAgentServer).ExecStream(m, &grpc.GenericServerStream[ExecRequest, ExecOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ExecStreamServer = grpc.ServerStreamingServer[ExecOutputChunk]

func _SandboxAgent_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_MakeDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).MakeDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_MakeDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).MakeDir(ctx, req.(*MakeDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PTYCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PTYCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PTYCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PTYCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PTYCreate(ctx, req.(*PTYCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PTYResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PTYResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PTYResize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PTYResize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PTYResize(ctx, req.(*PTYResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PTYKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PTYKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PTYKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PTYKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PTYKill(ctx, req.(*PTYKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SyncFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SyncFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SyncFS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SyncFS(ctx, req.(*SyncFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxAgent_ServiceDesc is the grpc.ServiceDesc for SandboxAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.SandboxAgent",
	HandlerType: (*SandboxAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _SandboxAgent_Exec_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SandboxAgent_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SandboxAgent_WriteFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _SandboxAgent_ListDir_Handler,
		},
		{
			MethodName: "MakeDir",
			Handler:    _SandboxAgent_MakeDir_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _SandboxAgent_Remove_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _SandboxAgent_Exists_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _SandboxAgent_Stat_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _SandboxAgent_Stats_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SandboxAgent_Ping_Handler,
		},
		{
			MethodName: "PTYCreate",
			Handler:    _SandboxAgent_PTYCreate_Handler,
		},
		{
			MethodName: "PTYResize",
			Handler:    _SandboxAgent_PTYResize_Handler,
		},
		{
			MethodName: "PTYKill",
			Handler:    _SandboxAgent_PTYKill_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _SandboxAgent_Shutdown_Handler,
		},
		{
			MethodName: "SyncFS",
			Handler:    _SandboxAgent_SyncFS_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _SandboxAgent_ExecStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent/agent.proto",
}
