// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxAgent_Exec_FullMethodName              = "/agent.SandboxAgent/Exec"
	SandboxAgent_ExecStream_FullMethodName        = "/agent.SandboxAgent/ExecStream"
	SandboxAgent_ReadFile_FullMethodName          = "/agent.SandboxAgent/ReadFile"
	SandboxAgent_WriteFile_FullMethodName         = "/agent.SandboxAgent/WriteFile"
	SandboxAgent_ReadFileStream_FullMethodName    = "/agent.SandboxAgent/ReadFileStream"
	SandboxAgent_WriteFileStream_FullMethodName   = "/agent.SandboxAgent/WriteFileStream"
	SandboxAgent_ListDir_FullMethodName           = "/agent.SandboxAgent/ListDir"
	SandboxAgent_MakeDir_FullMethodName           = "/agent.SandboxAgent/MakeDir"
	SandboxAgent_Remove_FullMethodName            = "/agent.SandboxAgent/Remove"
	SandboxAgent_Exists_FullMethodName            = "/agent.SandboxAgent/Exists"
	SandboxAgent_Stat_FullMethodName              = "/agent.SandboxAgent/Stat"
	SandboxAgent_Stats_FullMethodName             = "/agent.SandboxAgent/Stats"
	SandboxAgent_Ping_FullMethodName              = "/agent.SandboxAgent/Ping"
	SandboxAgent_PTYCreate_FullMethodName         = "/agent.SandboxAgent/PTYCreate"
	SandboxAgent_PTYResize_FullMethodName         = "/agent.SandboxAgent/PTYResize"
	SandboxAgent_PTYKill_FullMethodName           = "/agent.SandboxAgent/PTYKill"
	SandboxAgent_PTYAttach_FullMethodName         = "/agent.SandboxAgent/PTYAttach"
	SandboxAgent_ExecSessionCreate_FullMethodName = "/agent.SandboxAgent/ExecSessionCreate"
	SandboxAgent_ExecSessionAttach_FullMethodName = "/agent.SandboxAgent/ExecSessionAttach"
	SandboxAgent_ExecSessionList_FullMethodName   = "/agent.SandboxAgent/ExecSessionList"
	SandboxAgent_ExecSessionKill_FullMethodName   = "/agent.SandboxAgent/ExecSessionKill"
	SandboxAgent_SetEnvs_FullMethodName           = "/agent.SandboxAgent/SetEnvs"
	SandboxAgent_Shutdown_FullMethodName          = "/agent.SandboxAgent/Shutdown"
	SandboxAgent_SyncFS_FullMethodName            = "/agent.SandboxAgent/SyncFS"
	SandboxAgent_PrepareHibernate_FullMethodName  = "/agent.SandboxAgent/PrepareHibernate"
	SandboxAgent_SetResourceLimits_FullMethodName = "/agent.SandboxAgent/SetResourceLimits"
	SandboxAgent_GetVersion_FullMethodName        = "/agent.SandboxAgent/GetVersion"
	SandboxAgent_Upgrade_FullMethodName           = "/agent.SandboxAgent/Upgrade"
)

// SandboxAgentClient is the client API for SandboxAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxAgent runs inside each Firecracker microVM and handles
// exec, file ops, PTY, and stats over gRPC via vsock.
type SandboxAgentClient interface {
	// Exec runs a command and returns the result after completion.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// ExecStream runs a command and streams stdout/stderr chunks in real time.
	ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutputChunk], error)
	// Filesystem operations
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// Streaming file operations for large files (256KB chunks over vsock gRPC)
	ReadFileStream(ctx context.Context, in *ReadFileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	WriteFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileStreamRequest, WriteFileStreamResponse], error)
	ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error)
	MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Stats returns live resource usage from /proc.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Ping verifies the agent is responsive.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// PTY management (data flows over a separate vsock port per session)
	PTYCreate(ctx context.Context, in *PTYCreateRequest, opts ...grpc.CallOption) (*PTYCreateResponse, error)
	PTYResize(ctx context.Context, in *PTYResizeRequest, opts ...grpc.CallOption) (*PTYResizeResponse, error)
	PTYKill(ctx context.Context, in *PTYKillRequest, opts ...grpc.CallOption) (*PTYKillResponse, error)
	// PTYAttach opens a bidirectional stream for PTY I/O over gRPC.
	// Used by QEMU backend (virtio-serial) where vsock data ports are unavailable.
	PTYAttach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PTYInput, PTYOutput], error)
	// Exec sessions — persistent command execution with scrollback and reconnect.
	ExecSessionCreate(ctx context.Context, in *ExecSessionCreateRequest, opts ...grpc.CallOption) (*ExecSessionCreateResponse, error)
	ExecSessionAttach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecSessionInput, ExecSessionOutput], error)
	ExecSessionList(ctx context.Context, in *ExecSessionListRequest, opts ...grpc.CallOption) (*ExecSessionListResponse, error)
	ExecSessionKill(ctx context.Context, in *ExecSessionKillRequest, opts ...grpc.CallOption) (*ExecSessionKillResponse, error)
	// SetEnvs stores sandbox-level environment variables inside the agent.
	// These are injected into every subsequent Exec/ExecStream call,
	// between the base OS env and per-command envs.
	SetEnvs(ctx context.Context, in *SetEnvsRequest, opts ...grpc.CallOption) (*SetEnvsResponse, error)
	// Shutdown gracefully terminates the agent and syncs disks.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// SyncFS flushes all filesystem buffers without exiting.
	// Used before snapshot to ensure disk state is consistent.
	SyncFS(ctx context.Context, in *SyncFSRequest, opts ...grpc.CallOption) (*SyncFSResponse, error)
	// PrepareHibernate synchronously prepares the guest for hibernate/checkpoint:
	// syncs filesystems, flushes block device buffers, and quiesces the virtio-serial
	// listener so a clean Accept happens on wake/fork. Returns only after all work
	// completes — no sleep needed on the host side after this RPC.
	PrepareHibernate(ctx context.Context, in *PrepareHibernateRequest, opts ...grpc.CallOption) (*PrepareHibernateResponse, error)
	// SetResourceLimits adjusts sandbox cgroup limits at runtime.
	// Used for elastic scaling — raise/lower memory, CPU, pids without restart.
	SetResourceLimits(ctx context.Context, in *SetResourceLimitsRequest, opts ...grpc.CallOption) (*SetResourceLimitsResponse, error)
	// GetVersion returns the agent's build version.
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Upgrade replaces the agent binary and re-execs (same PID 1, no process loss).
	// The worker writes the new binary to binary_path before calling this.
	Upgrade(ctx context.Context, in *UpgradeRequest, opts ...grpc.CallOption) (*UpgradeResponse, error)
}

type sandboxAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxAgentClient(cc grpc.ClientConnInterface) SandboxAgentClient {
	return &sandboxAgentClient{cc}
}

func (c *sandboxAgentClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ExecStream(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutputChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[0], SandboxAgent_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecOutputChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ExecStreamClient = grpc.ServerStreamingClient[ExecOutputChunk]

func (c *sandboxAgentClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ReadFileStream(ctx context.Context, in *ReadFileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[1], SandboxAgent_ReadFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileStreamRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ReadFileStreamClient = grpc.ServerStreamingClient[FileChunk]

func (c *sandboxAgentClient) WriteFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileStreamRequest, WriteFileStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[2], SandboxAgent_WriteFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileStreamRequest, WriteFileStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_WriteFileStreamClient = grpc.ClientStreamingClient[WriteFileStreamRequest, WriteFileStreamResponse]

func (c *sandboxAgentClient) ListDir(ctx context.Context, in *ListDirRequest, opts ...grpc.CallOption) (*ListDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ListDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) MakeDir(ctx context.Context, in *MakeDirRequest, opts ...grpc.CallOption) (*MakeDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeDirResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_MakeDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PTYCreate(ctx context.Context, in *PTYCreateRequest, opts ...grpc.CallOption) (*PTYCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PTYCreateResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_PTYCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PTYResize(ctx context.Context, in *PTYResizeRequest, opts ...grpc.CallOption) (*PTYResizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PTYResizeResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_PTYResize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PTYKill(ctx context.Context, in *PTYKillRequest, opts ...grpc.CallOption) (*PTYKillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PTYKillResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_PTYKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PTYAttach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PTYInput, PTYOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[3], SandboxAgent_PTYAttach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PTYInput, PTYOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_PTYAttachClient = grpc.BidiStreamingClient[PTYInput, PTYOutput]

func (c *sandboxAgentClient) ExecSessionCreate(ctx context.Context, in *ExecSessionCreateRequest, opts ...grpc.CallOption) (*ExecSessionCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecSessionCreateResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ExecSessionCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ExecSessionAttach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecSessionInput, ExecSessionOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SandboxAgent_ServiceDesc.Streams[4], SandboxAgent_ExecSessionAttach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecSessionInput, ExecSessionOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ExecSessionAttachClient = grpc.BidiStreamingClient[ExecSessionInput, ExecSessionOutput]

func (c *sandboxAgentClient) ExecSessionList(ctx context.Context, in *ExecSessionListRequest, opts ...grpc.CallOption) (*ExecSessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecSessionListResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ExecSessionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) ExecSessionKill(ctx context.Context, in *ExecSessionKillRequest, opts ...grpc.CallOption) (*ExecSessionKillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecSessionKillResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_ExecSessionKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SetEnvs(ctx context.Context, in *SetEnvsRequest, opts ...grpc.CallOption) (*SetEnvsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetEnvsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_SetEnvs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SyncFS(ctx context.Context, in *SyncFSRequest, opts ...grpc.CallOption) (*SyncFSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncFSResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_SyncFS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) PrepareHibernate(ctx context.Context, in *PrepareHibernateRequest, opts ...grpc.CallOption) (*PrepareHibernateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareHibernateResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_PrepareHibernate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) SetResourceLimits(ctx context.Context, in *SetResourceLimitsRequest, opts ...grpc.CallOption) (*SetResourceLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResourceLimitsResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_SetResourceLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxAgentClient) Upgrade(ctx context.Context, in *UpgradeRequest, opts ...grpc.CallOption) (*UpgradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeResponse)
	err := c.cc.Invoke(ctx, SandboxAgent_Upgrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxAgentServer is the server API for SandboxAgent service.
// All implementations must embed UnimplementedSandboxAgentServer
// for forward compatibility.
//
// SandboxAgent runs inside each Firecracker microVM and handles
// exec, file ops, PTY, and stats over gRPC via vsock.
type SandboxAgentServer interface {
	// Exec runs a command and returns the result after completion.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// ExecStream runs a command and streams stdout/stderr chunks in real time.
	ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecOutputChunk]) error
	// Filesystem operations
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// Streaming file operations for large files (256KB chunks over vsock gRPC)
	ReadFileStream(*ReadFileStreamRequest, grpc.ServerStreamingServer[FileChunk]) error
	WriteFileStream(grpc.ClientStreamingServer[WriteFileStreamRequest, WriteFileStreamResponse]) error
	ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error)
	MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// Stats returns live resource usage from /proc.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Ping verifies the agent is responsive.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// PTY management (data flows over a separate vsock port per session)
	PTYCreate(context.Context, *PTYCreateRequest) (*PTYCreateResponse, error)
	PTYResize(context.Context, *PTYResizeRequest) (*PTYResizeResponse, error)
	PTYKill(context.Context, *PTYKillRequest) (*PTYKillResponse, error)
	// PTYAttach opens a bidirectional stream for PTY I/O over gRPC.
	// Used by QEMU backend (virtio-serial) where vsock data ports are unavailable.
	PTYAttach(grpc.BidiStreamingServer[PTYInput, PTYOutput]) error
	// Exec sessions — persistent command execution with scrollback and reconnect.
	ExecSessionCreate(context.Context, *ExecSessionCreateRequest) (*ExecSessionCreateResponse, error)
	ExecSessionAttach(grpc.BidiStreamingServer[ExecSessionInput, ExecSessionOutput]) error
	ExecSessionList(context.Context, *ExecSessionListRequest) (*ExecSessionListResponse, error)
	ExecSessionKill(context.Context, *ExecSessionKillRequest) (*ExecSessionKillResponse, error)
	// SetEnvs stores sandbox-level environment variables inside the agent.
	// These are injected into every subsequent Exec/ExecStream call,
	// between the base OS env and per-command envs.
	SetEnvs(context.Context, *SetEnvsRequest) (*SetEnvsResponse, error)
	// Shutdown gracefully terminates the agent and syncs disks.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// SyncFS flushes all filesystem buffers without exiting.
	// Used before snapshot to ensure disk state is consistent.
	SyncFS(context.Context, *SyncFSRequest) (*SyncFSResponse, error)
	// PrepareHibernate synchronously prepares the guest for hibernate/checkpoint:
	// syncs filesystems, flushes block device buffers, and quiesces the virtio-serial
	// listener so a clean Accept happens on wake/fork. Returns only after all work
	// completes — no sleep needed on the host side after this RPC.
	PrepareHibernate(context.Context, *PrepareHibernateRequest) (*PrepareHibernateResponse, error)
	// SetResourceLimits adjusts sandbox cgroup limits at runtime.
	// Used for elastic scaling — raise/lower memory, CPU, pids without restart.
	SetResourceLimits(context.Context, *SetResourceLimitsRequest) (*SetResourceLimitsResponse, error)
	// GetVersion returns the agent's build version.
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Upgrade replaces the agent binary and re-execs (same PID 1, no process loss).
	// The worker writes the new binary to binary_path before calling this.
	Upgrade(context.Context, *UpgradeRequest) (*UpgradeResponse, error)
	mustEmbedUnimplementedSandboxAgentServer()
}

// UnimplementedSandboxAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxAgentServer struct{}

func (UnimplementedSandboxAgentServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedSandboxAgentServer) ExecStream(*ExecRequest, grpc.ServerStreamingServer[ExecOutputChunk]) error {
	return status.Error(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedSandboxAgentServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSandboxAgentServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSandboxAgentServer) ReadFileStream(*ReadFileStreamRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadFileStream not implemented")
}
func (UnimplementedSandboxAgentServer) WriteFileStream(grpc.ClientStreamingServer[WriteFileStreamRequest, WriteFileStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFileStream not implemented")
}
func (UnimplementedSandboxAgentServer) ListDir(context.Context, *ListDirRequest) (*ListDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDir not implemented")
}
func (UnimplementedSandboxAgentServer) MakeDir(context.Context, *MakeDirRequest) (*MakeDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeDir not implemented")
}
func (UnimplementedSandboxAgentServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedSandboxAgentServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedSandboxAgentServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedSandboxAgentServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedSandboxAgentServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSandboxAgentServer) PTYCreate(context.Context, *PTYCreateRequest) (*PTYCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PTYCreate not implemented")
}
func (UnimplementedSandboxAgentServer) PTYResize(context.Context, *PTYResizeRequest) (*PTYResizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PTYResize not implemented")
}
func (UnimplementedSandboxAgentServer) PTYKill(context.Context, *PTYKillRequest) (*PTYKillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PTYKill not implemented")
}
func (UnimplementedSandboxAgentServer) PTYAttach(grpc.BidiStreamingServer[PTYInput, PTYOutput]) error {
	return status.Error(codes.Unimplemented, "method PTYAttach not implemented")
}
func (UnimplementedSandboxAgentServer) ExecSessionCreate(context.Context, *ExecSessionCreateRequest) (*ExecSessionCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecSessionCreate not implemented")
}
func (UnimplementedSandboxAgentServer) ExecSessionAttach(grpc.BidiStreamingServer[ExecSessionInput, ExecSessionOutput]) error {
	return status.Error(codes.Unimplemented, "method ExecSessionAttach not implemented")
}
func (UnimplementedSandboxAgentServer) ExecSessionList(context.Context, *ExecSessionListRequest) (*ExecSessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecSessionList not implemented")
}
func (UnimplementedSandboxAgentServer) ExecSessionKill(context.Context, *ExecSessionKillRequest) (*ExecSessionKillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecSessionKill not implemented")
}
func (UnimplementedSandboxAgentServer) SetEnvs(context.Context, *SetEnvsRequest) (*SetEnvsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEnvs not implemented")
}
func (UnimplementedSandboxAgentServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedSandboxAgentServer) SyncFS(context.Context, *SyncFSRequest) (*SyncFSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncFS not implemented")
}
func (UnimplementedSandboxAgentServer) PrepareHibernate(context.Context, *PrepareHibernateRequest) (*PrepareHibernateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareHibernate not implemented")
}
func (UnimplementedSandboxAgentServer) SetResourceLimits(context.Context, *SetResourceLimitsRequest) (*SetResourceLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetResourceLimits not implemented")
}
func (UnimplementedSandboxAgentServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedSandboxAgentServer) Upgrade(context.Context, *UpgradeRequest) (*UpgradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Upgrade not implemented")
}
func (UnimplementedSandboxAgentServer) mustEmbedUnimplementedSandboxAgentServer() {}
func (UnimplementedSandboxAgentServer) testEmbeddedByValue()                      {}

// UnsafeSandboxAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxAgentServer will
// result in compilation errors.
type UnsafeSandboxAgentServer interface {
	mustEmbedUnimplementedSandboxAgentServer()
}

func RegisterSandboxAgentServer(s grpc.ServiceRegistrar, srv SandboxAgentServer) {
	// If the following call panics, it indicates UnimplementedSandboxAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxAgent_ServiceDesc, srv)
}

func _SandboxAgent_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxAgentServer).ExecStream(m, &grpc.GenericServerStream[ExecRequest, ExecOutputChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ExecStreamServer = grpc.ServerStreamingServer[ExecOutputChunk]

func _SandboxAgent_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ReadFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SandboxAgentServer).ReadFileStream(m, &grpc.GenericServerStream[ReadFileStreamRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ReadFileStreamServer = grpc.ServerStreamingServer[FileChunk]

func _SandboxAgent_WriteFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxAgentServer).WriteFileStream(&grpc.GenericServerStream[WriteFileStreamRequest, WriteFileStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_WriteFileStreamServer = grpc.ClientStreamingServer[WriteFileStreamRequest, WriteFileStreamResponse]

func _SandboxAgent_ListDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ListDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ListDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ListDir(ctx, req.(*ListDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_MakeDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).MakeDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_MakeDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).MakeDir(ctx, req.(*MakeDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PTYCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PTYCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PTYCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PTYCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PTYCreate(ctx, req.(*PTYCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PTYResize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PTYResizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PTYResize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PTYResize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PTYResize(ctx, req.(*PTYResizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PTYKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PTYKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PTYKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PTYKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PTYKill(ctx, req.(*PTYKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PTYAttach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxAgentServer).PTYAttach(&grpc.GenericServerStream[PTYInput, PTYOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_PTYAttachServer = grpc.BidiStreamingServer[PTYInput, PTYOutput]

func _SandboxAgent_ExecSessionCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSessionCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ExecSessionCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ExecSessionCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ExecSessionCreate(ctx, req.(*ExecSessionCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ExecSessionAttach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SandboxAgentServer).ExecSessionAttach(&grpc.GenericServerStream[ExecSessionInput, ExecSessionOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SandboxAgent_ExecSessionAttachServer = grpc.BidiStreamingServer[ExecSessionInput, ExecSessionOutput]

func _SandboxAgent_ExecSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSessionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ExecSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ExecSessionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ExecSessionList(ctx, req.(*ExecSessionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_ExecSessionKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecSessionKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).ExecSessionKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_ExecSessionKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).ExecSessionKill(ctx, req.(*ExecSessionKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SetEnvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnvsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SetEnvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SetEnvs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SetEnvs(ctx, req.(*SetEnvsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SyncFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SyncFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SyncFS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SyncFS(ctx, req.(*SyncFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_PrepareHibernate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareHibernateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).PrepareHibernate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_PrepareHibernate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).PrepareHibernate(ctx, req.(*PrepareHibernateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_SetResourceLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetResourceLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).SetResourceLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_SetResourceLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).SetResourceLimits(ctx, req.(*SetResourceLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxAgent_Upgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxAgentServer).Upgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxAgent_Upgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxAgentServer).Upgrade(ctx, req.(*UpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxAgent_ServiceDesc is the grpc.ServiceDesc for SandboxAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.SandboxAgent",
	HandlerType: (*SandboxAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _SandboxAgent_Exec_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SandboxAgent_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SandboxAgent_WriteFile_Handler,
		},
		{
			MethodName: "ListDir",
			Handler:    _SandboxAgent_ListDir_Handler,
		},
		{
			MethodName: "MakeDir",
			Handler:    _SandboxAgent_MakeDir_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _SandboxAgent_Remove_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _SandboxAgent_Exists_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _SandboxAgent_Stat_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _SandboxAgent_Stats_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _SandboxAgent_Ping_Handler,
		},
		{
			MethodName: "PTYCreate",
			Handler:    _SandboxAgent_PTYCreate_Handler,
		},
		{
			MethodName: "PTYResize",
			Handler:    _SandboxAgent_PTYResize_Handler,
		},
		{
			MethodName: "PTYKill",
			Handler:    _SandboxAgent_PTYKill_Handler,
		},
		{
			MethodName: "ExecSessionCreate",
			Handler:    _SandboxAgent_ExecSessionCreate_Handler,
		},
		{
			MethodName: "ExecSessionList",
			Handler:    _SandboxAgent_ExecSessionList_Handler,
		},
		{
			MethodName: "ExecSessionKill",
			Handler:    _SandboxAgent_ExecSessionKill_Handler,
		},
		{
			MethodName: "SetEnvs",
			Handler:    _SandboxAgent_SetEnvs_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _SandboxAgent_Shutdown_Handler,
		},
		{
			MethodName: "SyncFS",
			Handler:    _SandboxAgent_SyncFS_Handler,
		},
		{
			MethodName: "PrepareHibernate",
			Handler:    _SandboxAgent_PrepareHibernate_Handler,
		},
		{
			MethodName: "SetResourceLimits",
			Handler:    _SandboxAgent_SetResourceLimits_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SandboxAgent_GetVersion_Handler,
		},
		{
			MethodName: "Upgrade",
			Handler:    _SandboxAgent_Upgrade_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _SandboxAgent_ExecStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadFileStream",
			Handler:       _SandboxAgent_ReadFileStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFileStream",
			Handler:       _SandboxAgent_WriteFileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PTYAttach",
			Handler:       _SandboxAgent_PTYAttach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ExecSessionAttach",
			Handler:       _SandboxAgent_ExecSessionAttach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/agent.proto",
}
